<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>BetterHardwareStats.Windows</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BetterHardwareStats.Core\BetterHardwareStats.Core.csproj" />
    <InternalsVisibleTo Include="BetterHardwareStats.Windows.Tests" />
    <!-- Use the stable local sensor library. -->
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
  </ItemGroup>
</Project>
