#!/usr/bin/env python3
"""Generates src/BetterHardwareStats.Core/Output/HardwareParameter.g.cs from parameters.txt.

Usage (from the repo root or anywhere):  python tools/gen-params/gen_params.py
Add --check to fail (exit 1) if the generated file is out of date instead of writing it.
Uses the Python standard library only.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
DATA = os.path.join(HERE, "parameters.txt")
OUT = os.path.join(ROOT, "src", "BetterHardwareStats.Core", "Output", "HardwareParameter.g.cs")
PREFIX = "VRCOSC/Hardware/"

TYPES = {"bool": "Bool", "int": "Int", "float": "Float"}
DOMAINS = {"GPU": "Gpu", "VRAM": "Gpu", "CPU": "Cpu", "RAM": "Ram", "Disk": "Disk", "Network": "Network"}
IDENT = re.compile(r"^[A-Z][A-Za-z0-9]*$")


def fail(msg):
    sys.stderr.write("gen_params: " + msg + "\n")
    sys.exit(2)


def parse(lines):
    rows = []
    block = None
    count = 0

    def add(cols, slot, lineno):
        if slot is not None:
            cols = [c.replace("{N}", str(slot)) for c in cols]
        elif any("{N}" in c for c in cols):
            fail("line %d: {N} outside an @slots block" % lineno)
        lookup, path, typ, parity, display, desc = cols
        if not IDENT.match(lookup):
            fail("line %d: bad lookup name %r" % (lineno, lookup))
        if typ not in TYPES:
            fail("line %d: bad type %r" % (lineno, typ))
        if parity not in ("yes", "no"):
            fail("line %d: parity must be yes or no" % lineno)
        domain = DOMAINS.get(path.split("/")[0])
        if domain is None:
            fail("line %d: unknown domain in %r" % (lineno, path))
        rows.append(dict(lookup=lookup, path=PREFIX + path, type=TYPES[typ], parity=parity == "yes",
                         display=display, desc=desc, domain=domain, slot=slot))

    for lineno, raw in enumerate(lines, 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("@slots"):
            if block is not None:
                fail("line %d: nested @slots" % lineno)
            count = int(line.split()[1])
            block = []
            continue
        if line == "@end":
            if block is None:
                fail("line %d: @end without @slots" % lineno)
            for slot in range(count):
                for ln, cols in block:
                    add(cols, slot, ln)
            block = None
            continue
        cols = [c.strip() for c in line.split("|")]
        if len(cols) != 6:
            fail("line %d: expected 6 columns, got %d" % (lineno, len(cols)))
        if block is not None:
            block.append((lineno, cols))
        else:
            add(cols, None, lineno)

    if block is not None:
        fail("unterminated @slots block")

    for key in ("lookup", "path"):
        seen = set()
        for r in rows:
            if r[key] in seen:
                fail("duplicate %s %r" % (key, r[key]))
            seen.add(r[key])
    return rows


def cs_string(s):
    if any(ord(ch) > 127 for ch in s):
        fail("non-ASCII text: %r" % s)
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(rows):
    out = []
    w = out.append
    w("// <auto-generated>")
    w("// Generated by tools/gen-params/gen_params.py from tools/gen-params/parameters.txt. Do not edit by hand.")
    w("// </auto-generated>")
    w("")
    w("namespace BetterHardwareStats.Core.Output;")
    w("")
    w("/// <summary>Parameter lookups (%d). Member names are persisted by VRCOSC; never rename after release.</summary>" % len(rows))
    w("public enum HardwareParameter")
    w("{")
    for r in rows:
        w("    %s," % r["lookup"])
    w("}")
    w("")
    w("public static partial class HardwareParameterTable")
    w("{")
    w("    public const int Count = %d;" % len(rows))
    w("")
    w("    public static IReadOnlyList<ParameterInfo> All { get; } =")
    w("    [")
    for r in rows:
        slot = "null" if r["slot"] is None else str(r["slot"])
        w("        new(HardwareParameter.%s, ParameterDomain.%s, %s, ParameterType.%s, %s, %s, %s, %s)," % (
            r["lookup"], r["domain"], slot, r["type"], cs_string(r["path"]), cs_string(r["display"]),
            cs_string(r["desc"]), "true" if r["parity"] else "false"))
    w("    ];")
    w("}")
    return "\n".join(out) + "\n"


def main():
    with open(DATA, encoding="ascii") as f:
        rows = parse(f.readlines())
    text = render(rows)
    if "--check" in sys.argv:
        try:
            with open(OUT, encoding="ascii", newline="") as f:
                current = f.read()
        except OSError:
            current = ""
        if current.replace("\r\n", "\n") != text:
            sys.stderr.write("gen_params: %s is out of date; run tools/gen-params/gen_params.py\n" % OUT)
            sys.exit(1)
        print("up to date (%d parameters)" % len(rows))
        return
    with open(OUT, "w", encoding="ascii", newline="\n") as f:
        f.write(text)
    print("wrote %s (%d parameters, %d parity)" % (os.path.relpath(OUT, ROOT), len(rows), sum(r["parity"] for r in rows)))


if __name__ == "__main__":
    main()
